#ifndef C8_EXCEPTION_HPP
#define C8_EXCEPTION_HPP

  /* Errorcodes */
  enum C8_EXCEPTION
  {
    C8_ILLEGAL_RAM_ACCESS,
    C8_ILLEGAL_REG_ACCESS,
    C8_ILLEGAL_OPCODE,
    C8_STACK_OVERFLOW,
    C8_STACK_UNDERRUN,
    C8_QUIT
  };

#endif
